title: "Aditi Joshi"
logo: /assets/img/aditi-joshi-profile-picture.jpg
description: "Portfolio of Aditi Joshi – Data Scientist and Engineer"
url: "https://aditi-joshi-usc.github.io"
baseurl: "/portfolio"
repository: "aditi-joshi-usc/portfolio"
favicon: /assets/img/favicon.ico

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Author info
author:
  name: "Aditi Joshi"
  avatar: /assets/img/aditi-joshi-profile-picture.jpg
  bio: "Data Engineer | ML & Cloud Enthusiast | USC Applied Data Science Grad"
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:aditi.jo2000@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/aditi-anant-joshi"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aditi-joshi-usc"

# Navigation
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      toc: true
      toc_sticky: true

# Appearance
minimal_mistakes_skin: "air"  # light, mint, air, dark, etc.
accent_color: "#6CA0DC"

# Footer
footer:
  links:
    - label: "GitHub"
      url: "https://github.com/aditi-joshi-usc"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/aditi-anant-joshi"

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X
