title: "Aditi Joshi"
logo: /assets/img/aditi-joshi-profile-picture.jpg
description: "Portfolio of Aditi Joshi – Data Scientist and Engineer"
url: "https://aditi-joshi-usc.github.io"
baseurl: "/portfolio"
repository: "aditi-joshi-usc/portfolio"

# Theme setup
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# SEO and Metadata
author:
  name: "Aditi Joshi"
  avatar: /assets/img/aditi-joshi-profile-picture.jpg
  bio: "Data Engineer & Scientist | AI | Cloud | Healthcare & FinTech"
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:aditi.jo2000@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/aditi-anant-joshi"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aditi-joshi-usc"

# Appearance
minimal_mistakes_skin: "air" # other nice options: "contrast", "sunrise", "aqua"
locale: "en-US"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# Analytics (optional)
# google_analytics: "UA-XXXXXXXXX-X"

# Navigation
header_pages:
  - index.md
  - projects.md
  - resume.md
  - contact.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"

# Accent color override (optional)
sass:
  style: compressed
  custom: |
    $primary-color: #6CA0DC;
    $text-color: #333;
    $link-color: #1F4B99;
    $background-color: #F4F9FF;
