title: "Aditi Joshi"
description: "Portfolio of Aditi Joshi – Data Scientist and Engineer"
url: "https://aditi-joshi-usc.github.io"
baseurl: "/portfolio"

logo: /assets/img/aditi-joshi-profile-picture.jpg
favicon: /assets/img/favicon.ico

# Theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins (required for remote_theme)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Appearance
accent_color: "#6CA0DC"

# Author Info
author:
  name: "Aditi Joshi"
  email: "aditi.jo2000@gmail.com"
  location: "Los Angeles, CA"
  links:
    - label: "GitHub"
      url: "https://github.com/aditi-joshi-usc"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/aditi-anant-joshi"
